### ISSUE TITLE
Find a better font

### ISSUE THREAD

**Issue by adarsh** [adarsh/blog#14]
cc @donokuda

**Comment by adarsh** [comment]
cc @gabebw - any suggestions?

**Comment by gabebw** [comment]
I use Calluna Sans on gabebw.com: http://www.exljbris.com/callunasans.html

It's free unless you want fancy font features (like, uh, real italics).

**Comment by donokuda** [comment]
Do you have a typekit account?

**Comment by adarsh** [comment]
I don't, should I?

Maybe I can write a post about how to select a font and install it in
Middleman?

@donokuda: how do you think about selecting a font? Where do you look,
what's the thought process?



-- 
@adarshp <http://www.twitter.com/adarshp>
313.454.1515 (mobile)
See when I am free: http://bit.ly/adarshcal

**Comment by donokuda** [comment]
Nope, there’s no need for typekit. You do get access to nicer typefaces in my opinion but there are some pretty good typefaces in Google Fonts.

Here are a couple that looked pretty good to me just as a drop-in.

Serif: https://www.google.com/fonts/specimen/Lora
![image](https://cloud.githubusercontent.com/assets/1174461/10963300/3f6a4eb2-8354-11e5-9a76-f9fdd98266b8.png)

Sans: https://www.google.com/fonts/specimen/Source+Sans+Pro
![screen shot 2015-11-05 at 12 17 28 am](https://cloud.githubusercontent.com/assets/1174461/10963290/26779860-8354-11e5-866d-7115a7238bf6.png)

I don’t have a pretty scientific method of choosing a typeface but normally I:

- Figure out what tone you want your font to communicate and what the font will be used for (header, body text)
- Look at typography pairings for inspiration
  - http://100daysoffonts.com/
  - http://justmytype.co/
  - http://www.typography.com/email/2010_03/index_tw.htm
- Use fonts by tried and tested foundries
  - FontFont (TypeKit)
  - Hoefler & Co. (Cloud Typography)
  - Mark Simonson (TypeKit)
- Mess around in Sketch.app until I’m finally happy.

**Comment by adarshp** [comment]
Hi,


I think I’m being accidentally included in these emails since my github username is adarshp - but I’m Adarsh Pyarelal, not Adarsh Pandit! So you may want to correct the email recipient list…




Best,

-Adarsh


-Adarsh
